name   = input("Nama : ")
nim    = input("NIM : ")
clas   = input("Kelas Paralel : ")
ttl    = input("Tempat/Tanggal Lahir : ")
address= input("Alamat : ")
hobby  = input("Hobby : ")
hp     = input("No. HP : ")

print("\nNama                    : ", nama)
print("NIM                     : ", nim)
print("Kelas Paralel           : ", kelas)
print("Tempat/Tanggal Lahirn   : ", ttl)
print("Alamat                  : ", alamat)
print("Hobby                   : ", hobby)
print("No. HP                  : ", hp)
