name   = input("Nama                   : ")
nim    = input("NIM                    : ")
clas   = input("Kelas Paralel          : ")
ttl    = input("Tempat/Tanggal Lahir   : ")
address= input("Alamat                 : ")
hobby  = input("Hobby                  : ")
hp     = input("No. HP                 : ")

print("\nNama                    : ", name)
print("NIM                     : ", nim)
print("Kelas Paralel           : ", clas)
print("Tempat/Tanggal Lahirn   : ", ttl)
print("Alamat                  : ", address)
print("Hobby                   : ", hobby)
print("No. HP                  : ", hp)
